### ISSUE TITLE
TFLite Conversion issues

### ISSUE THREAD

**Issue by SanthoshSandi** [Shathe/Semantic-Segmentation-Tensorflow-2#4]
Hello @Shathe . This is Santhosh. We tried out your mininet-V2 implementation for Segmentation using Tensorflow 2.0. We are able to successfully train the model. We have an use case to convert the same into TFLite, but when we try it, we run into issues. Herewith is attached, the issue when converting to TFLite according to the documentation provided by tensorflow

`Traceback (most recent call last):
  File "train.py", line 131, in <module>
    labels_resize_factor=labels_resize_factor)
  File "train.py", line 84, in train
    tflite_model = converter.convert()
  File "/media/babu/disk2/introtuce/venv_tf2/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 246, in convert
    self._func)
  File "/media/babu/disk2/introtuce/venv_tf2/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 173, in convert_variables_to_constants_v2
    "data": tensor_data[input_name],
KeyError: 'mini_netv2/mininet_v2downsample/conv_bn/batch_normalization_v2/FusedBatchNorm/ReadVariableOp/resource'
`

The following is the additional code we inserted to convert the training script to generate TFLite file.

`concrete_func = to_save.get_concrete_function(tensor_spec.TensorSpec([None, None, None, 3], dtypes.float32))`
`converter = lite.TFLiteConverterV2.from_concrete_function(concrete_func)`
`tflite_model = converter.convert()`
`open("converted_model.tflite","wb").write(tflite_model)`

Could you please help us in converting the same model. And if possible, could you share the benchmarking results of your model compared to Tensorflow's Official Deeplab model.

**Comment by Shathe** [comment]
Hi, 

It's a good thing that you  were able to train it :D 


Regarding the TFLite problem... I have never used it, why are you trying to do it? I do not know if I can help you there, sorry

Regarding the mininet-v2 performance... What do you mean? Comparing the results in what dataset? In fact this CNN and code it is just an example. And when you say Deeplab model, you mean deeplab, deeplabv2, deplabv3 or deeplabv3+?

**Comment by SanthoshSandi** [comment]
We are trying TFLite to deploy models on mobile devices. Segmentation with TF2.0 will be very much useful on deployment to mobile devices, as many layers have been upgraded.

Regarding the comparison, can you provide your benchmarking results in comparison withMobilenet-V2 based Deeplab-V3+ model, on Pascal VOC.
